replicaCount: 1

image:
  repository: gcr.io/lumen-microservices-migration/hello-world
  tag: "70"
  pullPolicy: IfNotPresent

deployment:
  name: spring-boot-helloworld
  port: 9091

service:
  name: spring-boot-helloworld
  type: NodePort
  port: 9091
  nodePort: 31000
