replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/lumen-microservices-migration/bmco/images/hello-world
  tag: "1"
  pullPolicy: IfNotPresent

deployment:
  name: spring-boot-helloworld
  port: 9091

service:
  name: spring-boot-helloworld
  type: NodePort
  port: 9091
  nodePort: 31000
