---
apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: hello-world-app
description: Hello World Deployment Pipeline
serialPipeline:
  stages:
  - targetId: dev-demos
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: dev-demos
description: Staging Environment
gke:
  cluster: projects/lumen-microservices-migration/locations/us-central1-a/clusters/dev-demos
